base_config:
  theme: "dark"
  margin: {top: 50, right: 110, bottom: 50, left: 60}
  xScale: {type: 'point'}
  yScale: {type: 'linear', min: 'auto', max: 'auto', stacked: True, reverse: False}
  yFormat: " >-.2f"
  axisTop: null
  axisRight: null
  axisBottom:
    tickSize: 5
    tickPadding: 5
    tickRotation: -45
    legend: 'Date'
    legendOffset: 45
    legendPosition: 'middle'
  axisLeft:
    tickSize: 5
    tickPadding: 5
    tickRotation: 0
    legend: 'Amount'
    legendOffset: -40
    legendPosition: 'middle'
  enableGridX: False
  enableGridY: True
  pointSize: 10
  pointColor: {theme: 'background'}
  pointBorderWidth: 2
  pointBorderColor: {from: 'serieColor'}
  pointLabelYOffset: -12
  useMesh: True
  legends:
    - anchor: 'bottom-right'
      direction: 'column'
      justify: False
      translateX: 100
      translateY: 0
      itemsSpacing: 2
      itemDirection: 'left-to-right'
      itemWidth: 80
      itemHeight: 20
      itemOpacity: 0.75
      symbolSize: 12
      symbolShape: 'circle'
      symbolBorderColor: 'rgba(0, 0, 0, .5)'
      effects:
        - on: 'hover'
          style:
            itemBackground: 'rgba(0, 0, 0, .03)'
            itemOpacity: 1

marker_config:
  animate: True
  curve: 'catmullRom'
  enableSlices: 'x'
  markers:
    - axis: 'y'
      legend: 'y marker'
      legendOrientation: 'vertical'
      lineStyle: {stroke: '#b0413e', strokeWidth: 2}
      value: 1000
    - axis: 'x'
      legend: 'x marker'
      lineStyle: {stroke: '#b0413e', strokeWidth: 2}
      value: '2019'
  theme: "dark"
  margin: {top: 50, right: 110, bottom: 50, left: 60}
  xScale: {type: 'point'}
  yScale: {type: 'linear', min: 'auto', max: 'auto', stacked: True, reverse: False}
  yFormat: " >-.2f"
  axisTop: null
  axisRight: null
  axisBottom:
    tickSize: 5
    tickPadding: 5
    tickRotation: -45
    legend: 'Date'
    legendOffset: 45
    legendPosition: 'middle'
  axisLeft:
    tickSize: 5
    tickPadding: 5
    tickRotation: 0
    legend: 'Amount'
    legendOffset: -40
    legendPosition: 'middle'
  enableGridX: False
  enableGridY: True
  pointSize: 10
  pointColor: {theme: 'background'}
  pointBorderWidth: 2
  pointBorderColor: {from: 'serieColor'}
  pointLabelYOffset: -12
  useMesh: True
  legends:
    - anchor: 'bottom-right'
      direction: 'column'
      justify: False
      translateX: 100
      translateY: 0
      itemsSpacing: 2
      itemDirection: 'left-to-right'
      itemWidth: 80
      itemHeight: 20
      itemOpacity: 0.75
      symbolSize: 12
      symbolShape: 'circle'
      symbolBorderColor: 'rgba(0, 0, 0, .5)'
      effects:
        - on: 'hover'
          style:
            itemBackground: 'rgba(0, 0, 0, .03)'
            itemOpacity: 1

divergence_chart_config:
  theme: "dark"
  animate: True
  areaOpacity: 0.07 #
  colors: #
    - 'rgb(97, 205, 187)'
    - 'rgb(244, 117, 96)'
  crosshairType: "cross" #
  curve: "monotoneX"
  enableArea: True
  enablePointLabel: True
  margin: {top: 50, right: 110, bottom: 50, left: 60}
  pointBorderColor:
    from: 'color'
    modifiers:
      - ['darker', 0.3]
  pointBorderWidth: 1
  pointLabelYOffset: -20
  pointSize: 14
  useMesh: True
  xScale:
    type: 'point'
    max: auto
    min: auto
  yScale:
    max: auto
    min: auto
    stacked: False
    type: 'linear'
  yFormat: " >-.2f"
  axisTop: null
  axisRight: null
  axisBottom:  
    tickSize: 5
    tickPadding: 5
    tickRotation: -45
    legend: 'Date'
    legendOffset: 45
    legendPosition: 'middle'
  axisLeft:  
    tickSize: 5
    tickPadding: 5
    tickRotation: 0
    legend: 'Amount'
    legendOffset: -40
    legendPosition: 'middle'
  enableGridX: False
  enableGridY: True
  legends:
    - anchor: 'bottom-right'
      direction: 'column'
      justify: False
      translateX: 110
      translateY: 0
      itemsSpacing: 1
      itemDirection: 'left-to-right'
      itemWidth: 80
      itemHeight: 20
      itemOpacity: 0.75
      symbolSize: 12
      symbolShape: 'circle'
      symbolBorderColor: 'rgba(0, 0, 0, .5)'
      effects:
        - on: 'hover'
          style:
            itemBackground: 'rgba(0, 0, 0, .03)'
            itemOpacity: 1

complex_time_chart_config:
  theme: "dark"  
  curve: "monotoneX" 
  enablePointLabel: False   
  animate: True
  axisBottom:
    format: '%Y-%m'
    legend: 'Date'
    legendOffset: 45
    tickValues: 'every 6 months'
    tickSize: 2
    tickPadding: 5
    tickRotation: -45
    legendPosition: 'middle'
  axisLeft:
    tickSize: 5
    tickPadding: 5
    tickRotation: 0
    legend: 'Amount'
    legendOffset: -50
    legendPosition: 'middle'
  margin: {top: 50, right: 110, bottom: 50, left: 60}
  pointBorderColor:
    from: 'color'
    modifiers: [['darker', 0.3]]
  pointLabelYOffset: -12
  pointBorderWidth: 2
  pointSize: 5
  useMesh: True
  xFormat: "time:%Y-%m"
  xScale:
    format: '%Y-%m'
    precision: 'month'
    type: 'time'
    useUTC: False
  yScale: {type: 'linear', min: 'auto', max: 'auto', stacked: True, reverse: False}
  yFormat: " >-.2f"  
  enableGridX: False  
  enableGridY: True   
  legends:           
    - anchor: 'bottom-right'
      direction: 'column'
      justify: False
      translateX: 85
      translateY: 0
      itemsSpacing: 2
      itemDirection: 'left-to-right'
      itemWidth: 80
      itemHeight: 20
      itemOpacity: 0.75
      symbolSize: 12
      symbolShape: 'circle'
      symbolBorderColor: 'rgba(0, 0, 0, .5)'
      effects:
        - on: 'hover'
          style:
            itemBackground: 'rgba(0, 0, 0, .03)'
            itemOpacity: 1

complex_chart_config_test:
  theme: "dark"
  animate: True
  areaOpacity: 0.07
  colors:
    - 'rgb(97, 205, 187)'
    - 'rgb(244, 117, 96)'
  crosshairType: "cross"
  curve: "monotoneX"
  enableArea: True
  enablePointLabel: True
  margin: {top: 50, right: 110, bottom: 50, left: 60}
  pointBorderColor:
    from: 'color'
    modifiers:
      - ['darker', 0.3]
  pointBorderWidth: 1
  pointLabelYOffset: -20
  pointSize: 14
  useMesh: True
  #xFormat: "time:%Y-%m"
  xScale:
    #format: '%Y-%m'
    #precision: 'month'
    type: 'point'
    useUTC: False
  yScale: {type: 'linear', min: 'auto', max: 'auto', stacked: False, reverse: False}
  yFormat: " >-.2f"
  axisTop: null
  axisRight: null
  axisBottom:
    #format: '%Y-%m'
    legend: 'Date'
    legendOffset: 45
    tickValues: 'every 6 months'
    tickSize: 2
    tickPadding: 5
    tickRotation: -45
    legendPosition: 'middle'
  axisLeft:
    tickSize: 5
    tickPadding: 5
    tickRotation: 0
    legend: 'Percent %'
    legendOffset: -50
    legendPosition: 'middle'
  enableGridX: False
  enableGridY: True
  legends:
    - anchor: 'bottom-right'
      direction: 'column'
      justify: False
      translateX: 110
      translateY: 0
      itemsSpacing: 1
      itemDirection: 'left-to-right'
      itemWidth: 80
      itemHeight: 20
      itemOpacity: 0.75
      symbolSize: 12
      symbolShape: 'circle'
      symbolBorderColor: 'rgba(0, 0, 0, .5)'
      effects:
        - on: 'hover'
          style:
            itemBackground: 'rgba(0, 0, 0, .03)'
            itemOpacity: 1
