CREATE VIEW IF NOT EXISTS cash_flow_yoy_growth AS
WITH preprocessed_data AS (
    SELECT *,
           LAG(CASH_FLOW_FINANCING, 4) OVER (PARTITION BY ENTITY ORDER BY DATE) AS Prev_CASH_FLOW_FINANCING,
           LAG(CASH_FLOW_INVESTING, 4) OVER (PARTITION BY ENTITY ORDER BY DATE) AS Prev_CASH_FLOW_INVESTING,
           LAG(CASH_FLOW_OPERATING, 4) OVER (PARTITION BY ENTITY ORDER BY DATE) AS Prev_CASH_FLOW_OPERATING
    FROM raw_cash_flow
)
SELECT
    ENTITY,
    CIK,
    DATE,
    Year,
    Quarter,
    CASH_FLOW_FINANCING,
    CASH_FLOW_INVESTING,
    CASH_FLOW_OPERATING,
    CASE WHEN Prev_CASH_FLOW_FINANCING IS NOT NULL THEN
        ROUND((CASH_FLOW_FINANCING - Prev_CASH_FLOW_FINANCING) / Prev_CASH_FLOW_FINANCING * 100, 2)
        ELSE NULL END AS CASH_FLOW_FINANCING_YoY,
    CASE WHEN Prev_CASH_FLOW_INVESTING IS NOT NULL THEN
        ROUND((CASH_FLOW_INVESTING - Prev_CASH_FLOW_INVESTING) / Prev_CASH_FLOW_INVESTING * 100, 2)
        ELSE NULL END AS CASH_FLOW_INVESTING_YoY,
    CASE WHEN Prev_CASH_FLOW_OPERATING IS NOT NULL THEN
        ROUND((CASH_FLOW_OPERATING - Prev_CASH_FLOW_OPERATING) / Prev_CASH_FLOW_OPERATING * 100, 2)
        ELSE NULL END AS CASH_FLOW_OPERATING_YoY
FROM preprocessed_data;
