CREATE VIEW IF NOT EXISTS cash_flow_summary_insights AS
SELECT *,
       (CASH_FLOW_FINANCING + CASH_FLOW_INVESTING + CASH_FLOW_OPERATING) AS Net_Cash_Flow,
       CASE WHEN (CASH_FLOW_FINANCING + CASH_FLOW_INVESTING + CASH_FLOW_OPERATING) > 0 THEN 1 ELSE 0 END AS Positive_Cash_Flow
FROM raw_cash_flow;
